### ISSUE TITLE
psMNIST

### ISSUE THREAD

**Issue by donghyunli** [zeyuliu1037/LMUFormer#2]
Hello, thank you for your amazing work. Could you share the code for training psMNIST with pre-processing? In SNN work, pre-processing should play an important role in good performance. Thank you.

**Comment by AnniLi1212** [comment]
Hi, thank you for your interest on our work. The jupyter notebook experiments on psMNIST is now uploaded to [src/LMUFormer_psMNIST.ipynb](https://github.com/zeyuliu1037/LMUFormer/blob/main/src/LMUFormer_psMNIST.ipynb). For the pre-processing we just used common transform methods and random permutations. If you have any questions, feel free to discuss!
